services:
  jobsaf-bot:
    build: .
    container_name: jobsaf-bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
    volumes:
      - ./data:/app/data
    networks:
      - traefik-global

networks:
  traefik-global:
    external: true
